[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
home=['<Super>e']
www=['<Super>b']

[custom-keybindings/custom0]
binding='<Super>t'
command='alacritty'
name='launch alacritty'
